<?php

namespace App\Models\Product;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class ProductImage extends Model
{
    protected $table = 'product_images';

    protected $fillable
        = [
            'link',
            'product_id',
            'alt',
            'order',
            'thumbnail'
        ];

    public function delete()
    {
        self::deleting(function ($image) {
            try {
                unlink(public_path($image->link));
            } catch (\Exception $exception) {

            }
        });

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
