<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CertificationImages extends Model
{
    protected $table = 'certification_images';

    protected $fillable
        = [
            'link',
            'certification_id',
            'alt',
            'order',
            'thumbnail'
        ];

    public function delete()
    {
        self::deleting(function ($image) {
            try {
                unlink(public_path($image->link));
            } catch (\Exception $exception) {

            }
        });

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
